### ISSUE TITLE
Error on getting data

### ISSUE THREAD

**Issue by ishikasingh** [Auquan/quant-quest-3#2]
Have updated the toolbox already.
Please check for this problem:-
`Traceback (most recent call last):
  File "problem1_template.py", line 6, in <module>
    from backtester.dataSource.csv_data_source import CsvDataSource
ImportError: No module named `csv_data_source`
`

**Comment by chandinijain** [comment]
Hey,

Are you on the most recent version of the toolbox? Try pip install -u auquan_toolbox and see if it works?

**Comment by ishikasingh** [comment]
Ma'am,
I tried that, I am running the code after updating the toolbox.

**Comment by chandinijain** [comment]
Adding @shubham1217 , please take a look

**Comment by ishikasingh** [comment]
Still unable to tackle that error. Seems like csv data source is not linked.
